[package]
name = "hello_http"
version = "0.1.0"
authors = ["mavensingh <kuldeep.avsar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
futures = "0.1"
serde_json = "1.0"